### PR TITLE
Add missing attr readers

### PR DESCRIPTION
**Pull request by dkapadia**
Adds missing attr_readers to allow ruby apps to access attributes from goals.

### CODE REVIEW

**Comment by kingdonb** [comment]
I'm not sure if there were more attributes added that this should expose, but I think this can be merged for 0.2.11.

**Comment by bsoule** [comment]
There are a bunch of other attributes listed for the goal resource in api.beeminder.com/#goal -- maybe we should be all completionist and make sure all of them are added.

**Comment by bsoule** [comment]
Ok, probably better to be expedient and merge this and we can add additional attribute accessors somewhere down the line.

**Comment by kingdonb** [comment]
Thanks for answering the question!  I'm going to mark http://bee.commits.to/new-beeminder-gem-release-v-2-11 as completed for you if you don't mind, even though rubygems says it came out as v0.2.12, and also attempt to be first at answering #23.

**Pull request merged**
